# Generated by Django 5.0.1 on 2024-02-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_hours',
        ),
    ]
