# Generated by Django 5.0.1 on 2024-02-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_hours',
        ),
    ]
